services:
  db:
    image: mysql:5.7
    container_name: spring-mysql
    ports:
      - 3304:3306  # 외부:내부
    environment:
      MYSQL_ROOT_PASSWORD: "root"    # DB 비밀번호 확인
      MYSQL_DATABASE: "memo_240627"  # DB명 확인
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - myapp_network

  application:
    container_name: myapp-test
    image: marobiana/myapp # 아까 생성한 이미지명 확인
    ports:
      - "8080:8080" # 외부:내부
    depends_on:
      - db
    volumes:
      - upload_volumes:/home/ec2-user/images
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/memo_240627?characterEncoding=UTF-8 # 내부 포트번호 일치
    networks:
      - myapp_network

volumes:
  upload_volumes:
  mysql_data:

networks:
  myapp_network: