# Java CI with Gradle & YAML Secrets

name: Java CI with Gradle

on:
  push:
    branches: [ "docker" ]
  pull_request:
    branches: [ "docker" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # YAML 파일 생성 단계 추가
    - name: Create security-variable.yml
      run: |
        echo "${{ secrets.SECURITY_VARIABLE }}" > ./src/main/resources/security-variable.yml

    # Gradle Build
    - name: Build with Gradle
      run: |
        chmod +x gradlew
        ./gradlew build -x test

    # Docker Build & Push
    - name: Docker build and push
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker build -t ${{ secrets.DOCKER_USERNAME }}/myapp .
        docker push ${{ secrets.DOCKER_USERNAME }}/myapp

    # Deploy to Server
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ec2-user
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
          sudo docker rm -f $(docker ps -qa)
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/myapp
          docker-compose up -d
          docker image prune -f
